# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90af6f147315b79b80a22b7976f162ab014f336f4cbecd8d899395de9a13fd851e95070b6476d14d3e1e9dd8bf90adf6e4d68ca1ae2e2634e6772dd63b5fa859

test:
  secret_key_base: e176a687cbdd511b337f724edf8986464916963fc3789e761ae9dc4f4f3ce04e513f039a98aa80d4811d70c18f0b303df0188800909640c2d4aaaaa4ad38e3ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
